network:
  ethernets:
    enp1s0:
      dhcp4: false
      dhcp6: false
      match:
        macaddress: fa:16:3e:27:7b:5a
        name: enp*s0
      set-name: enp1s0
    enp2s0:
      dhcp4: false
      dhcp6: false
      match:
        macaddress: fa:16:3e:2e:43:01
        name: enp*s0
      set-name: enp2s0
  version: 2
  vlans:
    enp1s0.200:
      addresses:
      - 192.168.200.181/24
      dhcp4: false
      dhcp6: false
      gateway4: 192.168.200.1
      id: 200
      link: enp1s0
      nameservers:
        addresses:
        - 192.168.1.10
        search:
        - cloud.local
    enp1s0.801:
      addresses:
      - 192.168.23.181/24
      dhcp4: false
      dhcp6: false
      id: 801
      link: enp1s0
    enp1s0.806:
      addresses:
      - 192.168.26.181/24
      dhcp4: false
      dhcp6: false
      id: 806
      link: enp1s0
  vrfs:
    vrf1:
      table: 10
      interfaces:
        - enp1s0.806
