network:
  ethernets:
    enp1s0:
      dhcp4: false
      dhcp6: false
      match:
        macaddress: fa:16:3e:0a:ae:f8
        name: enp*s0
      set-name: enp1s0
    enp2s0:
      dhcp4: false
      dhcp6: false
      match:
        macaddress: fa:16:3e:4f:dc:85
        name: enp*s0
      set-name: enp2s0
  version: 2
  vlans:
    enp1s0.200:
      addresses:
      - 192.168.200.182/24
      dhcp4: false
      dhcp6: false
      gateway4: 192.168.200.1
      id: 200
      link: enp1s0
      nameservers:
        addresses:
        - 192.168.1.10
        search:
        - cloud.local
    enp1s0.801:
      addresses:
      - 192.168.23.182/24
      dhcp4: false
      dhcp6: false
      id: 801
      link: enp1s0
    enp1s0.802:
      addresses:
      - 192.168.24.182/24
      dhcp4: false
      dhcp6: false
      id: 802
      link: enp1s0
    enp1s0.800:
      addresses:
      - 192.168.203.182/24
      dhcp4: false
      dhcp6: false
      id: 800
      link: enp1s0
  vrfs:
    vrf1:
      table: 10
      interfaces:
        - enp1s0.800
