FROM golang:1.16.6-buster AS builder

ENV APP_NAME web
WORKDIR /workspace

RUN go build -o ${APP_NAME}

RUN mkdir /app
RUN cp /workspace/web /app


FROM sregistry.iblog.pro/labs/alpine/lab.alpine:3.14-v1

ENV APP_NAME web
ENV PORT 8080

RUN mkdir /app
WORKDIR /app

COPY --from=builder /app/${APP_NAME} .
RUN chmod +x ./${APP_NAME}

EXPOSE 8080
CMD ["web"]
