{
 "title": "Blackbox Exporter Overview",
 "tags": [
  "blackbox",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "targets",
    "query": "label_values(probe_success, target)"
   }
  ]
 },
 "panels": [
  {
   "title": "Overall",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds and probe_success == 1",
     "legendFormat": "Probe {{ target }}"
    }
   ]
  },
  {
   "title": "Overall",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(probe_success[$interval])",
     "legendFormat": "Uptime {{ target }}"
    }
   ]
  },
  { "title": "$targets UP/DOWN Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }, "repeat": "targets" },
  {
   "title": "$targets",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{target=~\"$targets\"}"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_ssl{target=~\"$targets\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(probe_success{target=~\"$targets\"}[$interval])",
     "legendFormat": "success queries"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{target=~\"$targets\"} and probe_success{target=~\"$targets\"} == 1",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "SSL Cert Expiry",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 25 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{target=~\"$targets\"}-time()"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_status_code{target=~\"$targets\"}"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 29 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{target=~\"$targets\"})"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 29 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{target=~\"$targets\"})"
    }
   ]
  }
 ]
}