{
 "title": "Blackbox Exporter Dashboard 20220412-iBlog.pro",
 "description": "支持Grafana 8，基于blackbox_exporter 0.19.0设计；采用图表+曲线图方式展示TCP，ICMP，HTTPS的服务状态，各阶段请求延时，HTTPS证书信息等；优化展示效果，支持监控目标的分组、分类级联展示，多服务同时对比展示。",
 "tags": [
  "iBlog.pro",
  "blacbox_exporter"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "module",
    "label": "type",
    "query": {
     "query": "label_values(probe_success,module)"
    }
   },
   {
    "name": "company",
    "label": "Company",
    "query": {
     "query": "label_values(probe_success{module=~\"$module\"},company)"
    }
   },
   {
    "name": "project",
    "label": "Project",
    "query": {
     "query": "label_values(probe_success{module=~\"$module\",company=~\"$company\"},project)"
    }
   },
   {
    "name": "env",
    "label": "environment",
    "query": {
     "query": "label_values(probe_success{module=~\"$module\",company=~\"$company\",project=~\"$project\"},env)"
    }
   },
   {
    "name": "name",
    "label": "name",
    "query": {
     "query": "label_values(probe_success{module=~\"$module\",company=~\"$company\",project=~\"$project\",env=~\"$env\"},name)"
    }
   },
   {
    "name": "instance",
    "label": "Example",
    "query": {
     "query": "label_values(probe_success{module=~\"$module\",company=~\"$company\",project=~\"$project\",env=~\"$env\",name=~\"$name\"},instance)"
    }
   },
   {
    "name": "count",
    "query": {
     "query": "query_result(count(probe_success{module=~\"$module\",company=~\"$company\",project=~\"$project\",env=~\"$env\",name=~\"$name\",instance=~\"$instance\",instance=~\".*$sname.*\"}))"
    }
   },
   { "name": "sname", "label": "URL Screening (regular)" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status details, number of resources：$count",
   "type": "table",
   "description": "Note: For a URL with a REDIRECT, if the redirected domain name is different from the checked domain name, the checked certificate information is the redirected domain name certificate information.If you need to check the source domain name information, please add the disable redirect parameter to the blackbox.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "probe_success{module=~\"$module\",company=~\"$company\",project=~\"$project\",env=~\"$env\",name=~\"$name\",instance=~\"$instance\",instance=~\".*$sname.*\"} - 0"
    },
    {
     "expr": "probe_http_status_code{module=~\"$module\",company=~\"$company\",project=~\"$project\",env=~\"$env\",name=~\"$name\",instance=~\"$instance\",instance=~\".*$sname.*\"} - 0"
    },
    {
     "expr": "(probe_ssl_earliest_cert_expiry{module=~\"$module\",company=~\"$company\",project=~\"$project\",env=~\"$env\",name=~\"$name\",instance=~\"$instance\",instance=~\".*$sname.*\"}-time())/3600/24"
    },
    {
     "expr": "probe_http_version{module=~\"$module\",company=~\"$company\",project=~\"$project\",env=~\"$env\",name=~\"$name\",instance=~\"$instance\",instance=~\".*$sname.*\"} - 0"
    },
    {
     "expr": "probe_duration_seconds{module=~\"$module\",company=~\"$company\",project=~\"$project\",env=~\"$env\",name=~\"$name\",instance=~\"$instance\",instance=~\".*$sname.*\"} - 0"
    },
    {
     "expr": "sum_over_time(probe_success{module=~\"$module\",company=~\"$company\",project=~\"$project\",env=~\"$env\",name=~\"$name\",instance=~\"$instance\",instance=~\".*$sname.*\"}[60m])/count_over_time(probe_success{module=~\"$module\",company=~\"$company\",project=~\"$project\",env=~\"$env\",name=~\"$name\",instance=~\"$instance\",instance=~\".*$sname.*\"}[60m])"
    },
    {
     "expr": "probe_tls_version_info{module=~\"$module\",company=~\"$company\",project=~\"$project\",env=~\"$env\",name=~\"$name\",instance=~\"$instance\",instance=~\".*$sname.*\"}"
    },
    {
     "expr": "probe_dns_lookup_time_seconds{module=~\"$module\",company=~\"$company\",project=~\"$project\",env=~\"$env\",name=~\"$name\",instance=~\"$instance\",instance=~\".*$sname.*\"}-0"
    },
    {
     "expr": "probe_http_redirects{module=~\"$module\",company=~\"$company\",project=~\"$project\",env=~\"$env\",name=~\"$name\",instance=~\"$instance\",instance=~\".*$sname.*\"}-0"
    }
   ]
  },
  { "title": "Details $name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Connectivity proportion",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "count_values('value',probe_success{module=~\"$module\",company=~\"$company\",project=~\"$project\",env=~\"$env\",name=~\"$name\",instance=~\"$instance\",instance=~\".*$sname.*\"})"
    }
   ]
  },
  {
   "title": "Total inspection time $env $name",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 4, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{module=~\"$module\",company=~\"$company\",project=~\"$project\",env=~\"$env\",name=~\"$name\",instance=~\"$instance\",instance=~\".*$sname.*\"}",
     "legendFormat": "{{env}}_{{name}}"
    }
   ]
  },
  {
   "title": "ICMP/HTTPS The detection stage takes time $env $name",
   "type": "graph",
   "gridPos": { "h": 16, "w": 11, "x": 13, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_http_duration_seconds{module=~\"$module\",company=~\"$company\",project=~\"$project\",env=~\"$env\",name=~\"$name\",instance=~\"$instance\",instance=~\".*$sname.*\"}",
     "legendFormat": "{{env}}_{{name}} {{phase}}"
    }
   ]
  },
  {
   "title": "HTTP Status ratio",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "count_values('value',probe_http_status_code{module=~\"$module\",company=~\"$company\",project=~\"$project\",env=~\"$env\",name=~\"$name\",instance=~\"$instance\",instance=~\".*$sname.*\"})"
    }
   ]
  },
  {
   "title": "Website HTTP status check $env $name",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 4, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_http_status_code{module=~\"$module\",company=~\"$company\",project=~\"$project\",env=~\"$env\",name=~\"$name\",instance=~\"$instance\",instance=~\".*$sname.*\"}",
     "legendFormat": "{{env}}_{{name}} "
    }
   ]
  }
 ]
}