{
 "title": "blackbox_exporter-http-Dashboards-chinese",
 "description": "黑盒 http 监控面板",
 "tags": [
  "http/https",
  "blackbox_exporter",
  "web",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "project",
    "query": {
     "query": "label_values(probe_http_status_code, project)"
    }
   },
   { "name": "app", "label": "app", "query": { "query": "label_values(app)" } }
  ]
 },
 "panels": [
  { "title": "响应时间", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{project=~\"$project\", app=~\"$app\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "http/https 监控信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(probe_success{})" }
   ]
  },
  {
   "title": "Detailed Info",
   "type": "table",
   "gridPos": { "h": 13, "w": 20, "x": 4, "y": 9 },
   "targets": [
    {
     "expr": "probe_http_status_code{project=~\"$project\", app=~\"$app\"}"
    },
    {
     "expr": "probe_ssl_earliest_cert_expiry{project=~\"$project\", app=~\"$app\"} - time()"
    },
    {
     "expr": "probe_ssl_earliest_cert_expiry{project=~\"$project\", app=~\"$app\"} * 1000"
    },
    {
     "expr": "probe_duration_seconds{project=~\"$project\", app=~\"$app\"}"
    },
    {
     "expr": "probe_dns_lookup_time_seconds{project=~\"$project\", app=~\"$app\"}"
    },
    {
     "expr": "probe_success{project=~\"$project\", app=~\"$app\"}"
    },
    {
     "expr": "probe_tls_version_info{project=~\"$project\", app=~\"$app\", version=~\".*.1\"}"
    },
    {
     "expr": "probe_tls_version_info{project=~\"$project\", app=~\"$app\", version=~\".*.2\"}"
    },
    {
     "expr": "probe_tls_version_info{project=~\"$project\", app=~\"$app\", version=~\".*.3\"}"
    }
   ]
  },
  {
   "title": "Success",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success{project=~\"$project\", app=~\"$app\"} == 1)"
    }
   ]
  },
  {
   "title": "Fail",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success{project=~\"$project\", app=~\"$app\"} == 0)"
    }
   ]
  },
  {
   "title": "实例状态占比",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success{project=~\"$project\", app=~\"$app\"} == 1)",
     "legendFormat": "探测成功状态实例"
    },
    {
     "expr": "count(probe_success{project=~\"$project\", app=~\"$app\"} == 0)",
     "legendFormat": "探测失败状态实例"
    }
   ]
  },
  { "title": "证书即将到期的实例", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "证书不足30天过期",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{project=~\"$project\", app=~\"$app\"} - time() < (3600 * 24 * 30)"
    }
   ]
  },
  { "title": "响应码变化记录", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "响应码变化记录",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_http_status_code{project=~\"$project\", app=~\"$app\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}